#!/bin/bash

pushd "$(dirname $0)/../.." > /dev/null

# Store the current state of the git index
commit=$(git status --porcelain)

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
pushd client && cargo fmt --all && popd > /dev/null

# Check if anything to be commited was changed by the formatters
if [[ $(git status --porcelain) != "$commit" ]]; then
  echo "Code was formatted. Please review the changes and stage them before committing."
  exit 1
fi

popd > /dev/null
